Module4 task1
htmlacademy-nodejs/536599-typoteka-3 pull request #10
Opened 2020-11-14 16:44 UTC by RDemian

Внес правки, по комментариям к предыдущему пул-реквесту.

2020-11-15 12:57 UTC, dean992008 requested changes

2020-11-15 12:57 UTC, dean992008 commented on package.json
>      "moment": "^2.27.0",
https://up.htmlacademy.ru/nodejs/3/criteries#b24

2020-11-15 12:57 UTC, dean992008 commented on src/service/cli/help.js
> +    --generate <count>    формирует файл mocks.json
Нужно добавить команду `--server`.

2020-11-15 12:57 UTC, dean992008 commented on src/utils.js
>  module.exports.shuffle = (someArray) => {
Экспорт я бы делал в конце в виде обьекта: 
```
module.exports = {
  shuffle, 
  print,
  ...
}
```

2020-11-15 12:57 UTC, dean992008 commented on src/service/lib/get-mock-data.js
> +      const content = await fs.readFile(FILE_NAME);
При каждом вызове функции будет происходить чтение с диска, но это не очень хорошо. Лучше сделать чтобы при первом чтении с диска даные кешировались(сохранялись в переменую) и при повторном вызове возвращять с кеша.

2020-11-15 12:57 UTC, dean992008 commented on src/service/api/index.js
> +(async () => {
Думаю здесь будут проблемы когда начнем писать unit тесты, но поговорим об этом когда доберемся.

2020-11-21 08:46 UTC, RDemian commented on src/service/lib/get-mock-data.js
> +      const content = await fs.readFile(FILE_NAME);
Данные кешируются в переменной data. Перед чтением с диска есть проверка наличия данных в переменной data. Если в переменной data будут данные повторное чтение происходить не будет.

2020-11-21 09:05 UTC, RDemian commented on package.json
>      "moment": "^2.27.0",
поправил

2020-11-21 09:05 UTC, RDemian commented on src/service/cli/help.js
> +    --generate <count>    формирует файл mocks.json
поправил

2020-11-21 09:05 UTC, RDemian commented on src/service/api/index.js
> +(async () => {
поправил

2020-11-22 12:10 UTC, dean992008 commented on src/service/lib/get-mock-data.js
> +      const content = await fs.readFile(FILE_NAME);
Да недосмотрел)

2020-11-22 12:10 UTC, merged