Module4 task3
htmlacademy-nodejs/536599-typoteka-3 pull request #12
Opened 2020-12-06 18:53 UTC by RDemian

2020-12-07 20:56 UTC, dean992008 requested changes

2020-12-07 20:56 UTC, dean992008 commented on package.json
>      "supertest": "6.0.1"
Для удобства дальшейшей разрабочки рекомендую добавить скрипт который по npm start будет запускаться сразу 2 сервера. 
 https://www.npmjs.com/package/concurrently

2020-12-07 20:56 UTC, dean992008 commented on src/service/middlewares/body-validator.js
> +  console.log("keysExist2=", keysExist2)
Для логирования лучше использовать логгер, а если используешь для отладки то лучше настроить debbuger в vscode

2020-12-07 20:56 UTC, dean992008 commented on src/express/templates/partials/categories-row.pug
> +    li.themes__item
Правильнее вывести категории из апи, а количество пока сделать случайно цыфрой.

2020-12-07 20:56 UTC, dean992008 commented on src/express/templates/main.pug
> +              li.preview__breadcrumbs-item
Нужно выводить категории за АПИ, из поля `сategory`

2020-12-07 20:56 UTC, dean992008 commented on src/express/templates/main.pug
> +              img.preview__background-image(src='img/skyscraper@1x.jpg' width='460' height='240' srcset='img/skyscraper@1x.jpg, img/skyscraper@2x.jpg 2x' alt='Фотография небоскреба')
Для картинок я бы пока использовал: https://picsum.photos/, чтобы сделать рандомные картинки, реальные помоему мы не будем добавлять.

2020-12-07 20:57 UTC, dean992008 commented
В целом все правильно сделал, пару мелочей по косметике нужно поправить.

2020-12-11 05:19 UTC, RDemian commented on package.json
>      "supertest": "6.0.1"
добавил npm run start-all

2020-12-11 05:20 UTC, RDemian commented on src/service/middlewares/body-validator.js
> +  console.log("keysExist2=", keysExist2)
удалил, отладочную инфу

2020-12-12 16:41 UTC, RDemian commented on src/express/templates/partials/categories-row.pug
> +    li.themes__item
вывел из апи

2020-12-12 17:21 UTC, RDemian commented on src/express/templates/main.pug
> +              li.preview__breadcrumbs-item
я вывел в этом месте категории, но чет не пойму это точно категории? Написано хлебные крошки...

2020-12-12 17:21 UTC, RDemian commented on src/express/templates/main.pug
> +              img.preview__background-image(src='img/skyscraper@1x.jpg' width='460' height='240' srcset='img/skyscraper@1x.jpg, img/skyscraper@2x.jpg 2x' alt='Фотография небоскреба')
добавил

2020-12-13 11:58 UTC, merged